FROM node:22-bookworm-slim AS builder

WORKDIR /app
COPY . .
RUN npm ci
RUN npm run generate:db
RUN npm run build --workspace backend

FROM node:22-bookworm-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=8080

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/backend/dist ./apps/backend/dist
COPY --from=builder /app/apps/backend/package.json ./apps/backend/package.json
COPY --from=builder /app/packages/db ./packages/db
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/apps/backend/src/covers ./apps/backend/src/covers
COPY --from=builder /app/apps/backend/src/fonts ./apps/backend/src/fonts

RUN mkdir -p /app/apps/backend/assets/pdfs /app/apps/backend/assets/previews /app/apps/backend/assets/covers
EXPOSE 8080
CMD ["node", "apps/backend/dist/index.js"]
